using System;

namespace MarketDataFramework.Core.Models
{
    /// <summary>
    /// Atomic unit of market data: a price contribution from a feed at a precise timestamp.
    /// In high-frequency context, multiple ticks per instrument can arrive within the same
    /// population window (100ms slice).
    /// </summary>
    public class MarketDataTick
    {
        /// <summary>Instrument this tick belongs to.</summary>
        public string InstrumentIsin { get; set; }

        /// <summary>
        /// Mid price (bid/ask midpoint) or last traded price.
        /// Expressed in basis points for government bonds.
        /// </summary>
        public double Price { get; set; }

        /// <summary>Bid side of the market.</summary>
        public double Bid { get; set; }

        /// <summary>Ask side of the market.</summary>
        public double Ask { get; set; }

        /// <summary>
        /// Precise timestamp of the contribution from the upstream feed.
        /// Critical for stochastic clock population delimitation.
        /// </summary>
        public DateTime Timestamp { get; set; }

        /// <summary>Source feed identifier (Bloomberg, Reuters, internal).</summary>
        public string FeedSource { get; set; }

        /// <summary>
        /// True if this tick was generated by extrapolation rather than
        /// an actual market contribution. Consumers can filter on this.
        /// </summary>
        public bool IsExtrapolated { get; set; }

        public MarketDataTick() { }

        public MarketDataTick(string isin, double price, DateTime timestamp, string feedSource)
        {
            InstrumentIsin = isin;
            Price          = price;
            Bid            = price;
            Ask            = price;
            Timestamp      = timestamp;
            FeedSource     = feedSource;
            IsExtrapolated = false;
        }

        /// <summary>
        /// Mid price computed from bid/ask spread.
        /// Falls back to Price if bid or ask is not set.
        /// </summary>
        public double MidPrice
        {
            get
            {
                if (Bid > 0 && Ask > 0)
                    return (Bid + Ask) / 2.0;
                return Price;
            }
        }

        public override string ToString()
        {
            return string.Format("{0} @ {1:F6} [{2}] {3}",
                InstrumentIsin, Price,
                Timestamp.ToString("HH:mm:ss.fff"),
                IsExtrapolated ? "(EXTRAPOLATED)" : string.Empty);
        }
    }
}
